import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="p-4 text-2xl font-bold text-center bg-amber-200">
          <Navigation />
        </header>
        {children}
        <footer className="p-4 text-center bg-amber-200">
          <div className="text-2xl font-bold">Footer</div>
          <div className="text-xs">copyright &copy; 2025 </div>
        </footer>
      </body>
    </html>
  );
}
